### ISSUE TITLE
computer memory

### ISSUE THREAD

**Issue by jujuran2** [paleckar/matlab-dlib-facetrack#2]
I use your code to detect faces in the video, I find that the computer's memory usage is getting higher and higher until the computer freezes.

**Comment by paleckar** [comment]
I'm unable to reproduce this issue. Could you please post minimal code that leaks memory? Similar issue has already been dealt with in #1 .

Please create a new detector instance `h = detector('new', 'shape_predictor_68_face_landmarks.dat')` only once at the beginning of the video. Also, make sure the old instance is properly deleted using `detector('delete', h)` before assigning a new one to the same variable `h`.
