### ISSUE TITLE
Unrecognized function or variable 'detector'.

### ISSUE THREAD

**Issue by a-mouk** [paleckar/matlab-dlib-facetrack#3]
" Unrecognized function or variable 'detector'. "
I get this error. Is something missing?

**Comment by paleckar** [comment]
The `test_image.m` script works as expected on my Ubuntu 18.04 with MATLAB R2020a. Make sure that you have the `detector.mexa64` (Linux) or `detector.mexw64` (Windows) in the working directory.

**Comment by a-mouk** [comment]
Oh I'm sorry, i had forgotten to move detector.mexw64 to working directory, indeed. Thank you. Very nice job
